{
    "name": "My Estate",
    "version": "19.0.1.0.0",
    "summary": "Test my custom module",
    "category": "Real Estate",
    "author": "Linh",
    "license": "LGPL-3",
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "report/estate_property_report.xml",
        "views/estate_menus.xml",
        "wizard/estate_property_cancel_wizard_views.xml",
        "views/estate_property_offer_views.xml",
        "views/estate_property_views.xml",
        "views/estate_property_type_views.xml",
        "views/estate_property_tag_views.xml",
        "views/estate_website_templates.xml",
    ],
    "depends": ["base", "website", "mail", "portal"],
    "application": True,
    "installable": True,
}
